services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=dev-mem
      - KC_HTTP_ENABLED=true
      - KEYCLOAK_EXTERNAL_URL=https://keycloak-api.joseserver.com
      - KC_HOSTNAME=https://keycloak-api.joseserver.com
      - KC_HOSTNAME_URL=${KEYCLOAK_EXTERNAL_URL}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_ADMIN_URL=${KEYCLOAK_EXTERNAL_URL}
      - KC_HTTP_RELATIVE_PATH=/
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    command: start-dev
    # Healthcheck removed - curl not available in container
    # Health is checked from host in Makefile instead
    networks:
      - demo-network

  consent-store:
    build: ./consent-store
    container_name: consent-store
    ports:
      - "${CONSENT_STORE_PORT:-8001}:8001"
    volumes:
      - ./consent-store-data:/app/data
      - ./config.py:/app/config.py
    networks:
      - demo-network
    depends_on:
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PYTHONUNBUFFERED=1
      - EXTERNAL_IP=${EXTERNAL_IP}
      - FRONTEND_EXTERNAL_IP=${FRONTEND_EXTERNAL_IP}
      - FRONTEND_EXTERNAL_URL=${FRONTEND_EXTERNAL_URL}

  banking-service:
    image: python:3.11-slim
    container_name: banking-service
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && 
             python banking-service.py"
    ports:
      - "${BANKING_SERVICE_PORT:-8012}:8012"
    volumes:
      - ./banking-service.py:/app/banking-service.py
      - ./requirements.txt:/app/requirements.txt
      - ./banking-service-templates:/app/banking-service-templates
      - ./config.py:/app/config.py
    networks:
      - demo-network
    depends_on:
      - keycloak
    environment:
      - PYTHONUNBUFFERED=1
      - EXTERNAL_IP=${EXTERNAL_IP}
      - FRONTEND_EXTERNAL_IP=${FRONTEND_EXTERNAL_IP}
      - CONSENT_STORE_INTERNAL_URL=${CONSENT_STORE_INTERNAL_URL}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - BANKING_SERVICE_PORT=${BANKING_SERVICE_PORT}

  hello:
    image: python:3.11-slim
    container_name: hello
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && 
             python hello.py"
    ports:
      - "${HELLO_SERVICE_PORT:-8003}:8003"
    volumes:
      - ./hello.py:/app/hello.py
      - ./requirements.txt:/app/requirements.txt
      - ./config.py:/app/config.py
    networks:
      - demo-network
    environment:
      - PYTHONUNBUFFERED=1
      - EXTERNAL_IP=${EXTERNAL_IP}
      - FRONTEND_EXTERNAL_IP=${FRONTEND_EXTERNAL_IP}
      - FRONTEND_EXTERNAL_URL=${FRONTEND_EXTERNAL_URL}

  service-a:
    image: python:3.11-slim
    container_name: service-a
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && 
             python service-a.py"
    ports:
      - "${SERVICE_A_PORT:-8004}:8004"
    volumes:
      - ./service-a.py:/app/service-a.py
      - ./requirements.txt:/app/requirements.txt
      - ./config.py:/app/config.py
    networks:
      - demo-network
    depends_on:
      - consent-store
      - banking-service
    environment:
      - PYTHONUNBUFFERED=1
      - CLIENT_SECRET=${SERVICE_A_CLIENT_SECRET}
      - KEYCLOAK_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-master}
      - EXTERNAL_IP=${EXTERNAL_IP}
      - FRONTEND_EXTERNAL_IP=${FRONTEND_EXTERNAL_IP}
      - BANKING_SERVICE_EXTERNAL_URL=${BANKING_SERVICE_EXTERNAL_URL}
      - FRONTEND_EXTERNAL_URL=${FRONTEND_EXTERNAL_URL}

  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "${FRONTEND_PORT:-3005}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - demo-network
    depends_on:
      - keycloak
      - service-a
      - hello
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env.local

networks:
  demo-network:
    driver: bridge

volumes:
  consent-store-data:
